### ISSUE TITLE
 Bug 113 - swftocxx don`t care about objects redeclarations

### ISSUE THREAD

**Issue by netsweng** [libming/libming#36]
lion 2011-06-29 23:05:54 EDT

When compile output of swftocxx with many flashes I get thousand of errors
like:

test.cpp:2381:10: error: redeclaration of ‘SWFFont\* f6’
test.cpp:2378:10: error: ‘SWFFont\* f6’ previously declared here

It seems swftocxx don`t care about redeclarations at all.

Also there deprecation warnings:

mingpp.h: In member function ‘char\* SWFFont::getShape(short unsigned int)’:
mingpp.h:856:14: warning: ‘char\* SWFFont_getShape(c_SWFFont, short unsigned
int)’ is deprecated (declared at ming.h:445) [-Wdeprecated-declarations]
mingpp.h:856:44: warning: ‘char\* SWFFont_getShape(c_SWFFont, short unsigned
int)’ is deprecated (declared at ming.h:445) [-Wdeprecated-declarations]

and default parameters problems:

test.cpp:2577:26: error: no matching function for call to
‘SWFShape::setRightFill()’
test.cpp:2577:26: note: candidate is:
mingpp.h:1369:8: note: void SWFShape::setRightFill(SWFFill*)
mingpp.h:1369:8: note:   candidate expects 1 argument, 0 provided

**Comment by strk** [comment]
Is this still an issue ? If so, can you provide a testcase ? (and check if #54 fixes this)

**Comment by strk** [comment]
Closing due to lack of feedback.
