### ISSUE TITLE
Dead homepage. Dead project?

### ISSUE THREAD

**Issue by rbalint** [libming/libming#62]
Hi,

Thank you for libming.
I afraid the project's homepage is down:
http://www.libming.org

There is also little activity here on GitHub, PR-s are not accepted nor commented on.
Please resurrect the development within the original team or at least give merge rights to some people sending PR-s. There is interest in keeping the project alive but this needs at least someone accepting patches.

Cheers,
Balint

**Comment by strk** [comment]
Sorry, I just realized I wasn't watching, now started to watch.
If you want to help you're welcome !

**Comment by rbalint** [comment]
@strk Thanks!
I have already provided PR for the CVEs

**Comment by rbalint** [comment]
libming has been removed from Debian but it can reenter if development becomes active and when code looks good security-wise.

**Comment by strk** [comment]
@rbalint if you want to help co-maintaining Ming I'm happy to share powers

**Comment by rbalint** [comment]
@strk Thanks for the kind offer. I have fixed the outstanding security issues as part of the Debian LTS project but otherwise I don't use libming thus I think I'm not the right person to become a co-maintainer.
