### ISSUE TITLE
please issue a new release

### ISSUE THREAD

**Issue by asarubbo** [libming/libming#67]
Would be great to have a new release to test if the security bugs were really fixed or not.

Also, before make the new release would be awesome if #55 and #56 are fixed.

Thanks.

**Comment by strk** [comment]
I can only apply existing patches, won't work on more myself.
Maybe you can help testing #61 ?

**Comment by strk** [comment]
0.4.8 released: https://github.com/libming/libming/releases/tag/ming-0_4_8
